 
title: Acevedo Lopez Oscar
email: oscar.acevedo@comunidad.unam.mx
description: > # this means to ignore newlines until "baseurl:"
  This page is my page which serves as a portfolio and a blog for my interests.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://acevedo-oscar.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  acevedo-oscar

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
